name: Node.js CI

on: workflow_dispatch

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        run: pnpm install

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js with cache
        uses: ./.github/actions/setup-node
        with:
          restore-cache: "true"

      - name: Build
        run: pnpm build

  security-scan:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js with cache
        uses: ./.github/actions/setup-node
        with:
          restore-cache: "true"

      - name: Aqua Security Trivy Install
        uses: aquasecurity/setup-trivy@v0.2.3

      - name: Run pnpm audit
        run: pnpm audit-report

      - name: Archive pnpm audit results
        uses: actions/upload-artifact@v4
        with:
          name: audit-report
          path: audit-report.html

      - name: Run SAST
        run: pnpm trivy-report

      - name: Archive SAST results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt

  fake-ansible-deploy:
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Ansible
        uses: alex-oleshkevich/setup-ansible@v1.0.1
        with:
          version: latest

      - name: Run Ansible
        run: ansible -i ops/ansible/inventory.yml ops/ansible/playbook.yml

  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Setup Node.js with cache
        uses: ./.github/actions/setup-node
        with:
          restore-cache: "true"
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
